apiVersion: v1
appVersion: V.0.1
description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.&#039;'
name: memo
version: 0.1.0
home: memo.zaakonline.nl
icon: memo.zaakonline.nl
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
      condition: postgresql.enabled