annotations:
    artifacthub.io/containsSecurityUpdates: "true"
apiVersion: v2
appVersion: V1.0
description: 'Het Memo Component biedt de generieke mogelijkheid om gebruikers memo’s (notities) te laten aanmaken of resources (bijvoorbeeld Common Ground resources). Deze functionaliteit is bewust abstract opgezet. In wezen kan elke gebruiker over alles een memo aanmaken. Dat biedt ook de mogelijkheid om voor elke willekeurige resource het component te bevragen en te zien of er memo’s voor staan. Memo’s worden in principe gezien als organisatie-intern en zijn nadrukkelijk geen communicatiekanaal met de klant, daarvoor zijn ‘contactmomenten’ beschikbaar.'
name: memo-component
version: 1.0.0
home: https://www.conduction.nl
icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
keywords:
    - commonground
    - haven
    - nlx
    - component
maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
      condition: postgresql.enabled
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 12.7.7
      condition: redis.enabled